### ISSUE TITLE
@sap-ux/ui5-middleware-fe-mockserver

### ISSUE THREAD

**Issue by heimwege** [SAP-samples/fiori-tools-samples#13]
Hi guys,

the [@sap-ux/ui5-middleware-fe-mockserver](https://www.npmjs.com/package/@sap-ux/ui5-middleware-fe-mockserver) npm points to this repo as sample application but this repo uses the deprecated [@sap/ux-ui5-fe-mockserver-middleware](https://www.npmjs.com/package/@sap/ux-ui5-fe-mockserver-middleware) in both V2 apps (see [here](https://github.com/SAP-samples/fiori-tools-samples/blob/main/V2/apps/store-overview/package.json#L17))

Cheers
Dominik

**Comment by gregorwolf** [comment]
Created #14 to fix this issue.

**Comment by nlunets** [comment]
Thanks for raising this, #14 is approved from my point of view but i cannot merge it :)
